# Generated by Django 4.2.3 on 2023-07-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='url_image',
            field=models.TextField(default='https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTVcKAm-JAZ7SMJEEoZyPfRu2qPYwIysAHNI6neFZlfZManK7Kx'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
